// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTneg0EwPykDjLSCowP0ffGsqDU2lvGjs',
    appId: '1:137029580333:web:bb69b4d73726504f962aa4',
    messagingSenderId: '137029580333',
    projectId: 'babylon-11a77',
    authDomain: 'babylon-11a77.firebaseapp.com',
    storageBucket: 'babylon-11a77.firebasestorage.app',
    measurementId: 'G-ZRC1VGE81T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8GV8HHitMf8g_fNdxkFxczB5RT6WWlUE',
    appId: '1:137029580333:android:57f8d8d90887904d962aa4',
    messagingSenderId: '137029580333',
    projectId: 'babylon-11a77',
    storageBucket: 'babylon-11a77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaBiDp_Ywf2N0VywSWMGBwkYWlEWyuQVk',
    appId: '1:137029580333:ios:73425b09cd7ba346962aa4',
    messagingSenderId: '137029580333',
    projectId: 'babylon-11a77',
    storageBucket: 'babylon-11a77.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaBiDp_Ywf2N0VywSWMGBwkYWlEWyuQVk',
    appId: '1:137029580333:ios:73425b09cd7ba346962aa4',
    messagingSenderId: '137029580333',
    projectId: 'babylon-11a77',
    storageBucket: 'babylon-11a77.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTneg0EwPykDjLSCowP0ffGsqDU2lvGjs',
    appId: '1:137029580333:web:803629e0ad8e72e5962aa4',
    messagingSenderId: '137029580333',
    projectId: 'babylon-11a77',
    authDomain: 'babylon-11a77.firebaseapp.com',
    storageBucket: 'babylon-11a77.firebasestorage.app',
    measurementId: 'G-Z5912SPQX5',
  );
}
